version: '3'
services:
  backend:
    build: ./backend
    volumes:
      - ./backend/db.sqlite3:/app/db.sqlite3
    ports:
      - "8000:8000"
  frontend:
    build: ./frontend
    ports:
      - "80:80"
    depends_on:
      - backend
